In [4]:
import numpy as np
import pandas as pd
df=pd.read_csv("production_analysis_dataset.csv")
df.columns

Index(['production_id', 'product_category', 'factory', 'shift', 'supervisor',
       'units_produced', 'defective_units', 'production_time_hr',
       'machine_downtime_hr', 'energy_consumption_kwh', 'profit'],
      dtype='object')

# Q1. Find the total units produced by each product_category.

In [5]:
df.groupby("product_category")[ 'units_produced'].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

# Q2. Calculate the average profit for each factory.

In [6]:
df.groupby("factory")["profit"].mean()

factory
Plant_A    18044.375000
Plant_B    16973.384615
Plant_C    18086.076923
Name: profit, dtype: float64

# Q3. Find the total defective_units for each shift.

In [8]:
df.groupby("shift")['defective_units'].sum()

shift
Evening    132
Morning    472
Night      471
Name: defective_units, dtype: int64

# Q4. Calculate the average production_time_hr for each supervisor.

In [11]:
df.groupby('supervisor')['production_time_hr'].mean()

supervisor
S1    7.801818
S2    7.450000
S3    7.882000
S4    7.956154
Name: production_time_hr, dtype: float64

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [13]:
df.groupby(['factory','shift'])['energy_consumption_kwh'].sum()

factory  shift
Plant_A  Evening     3330
         Morning    11144
         Night      12913
Plant_B  Evening     2889
         Morning     7923
         Night       4981
Plant_C  Evening     2214
         Morning     5632
         Night       7363
Name: energy_consumption_kwh, dtype: int64

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

In [16]:
# aggregation
df.groupby("product_category").agg({"units_produced":"sum","profit":"mean","defective_units":'max'})

                  units_produced        profit  defective_units
product_category
Automotive                  9408  18374.722222               34
Electronics                 7491  16945.750000               40
Furniture                   7251  17935.062500               39

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

In [19]:
df.groupby("factory").agg({"machine_downtime_hr":"median","production_time_hr":"mean"})

         machine_downtime_hr  production_time_hr
factory
Plant_A                0.945            7.890000
Plant_B                1.070            7.579231
Plant_C                0.850            7.810769

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

In [23]:
df.groupby("shift").agg({"profit":['min','max'],"units_produced":"max"})

        profit        units_produced
           min    max            max
shift
Evening  10009  22302            690
Morning  10722  24358            665
Night    12045  24586            666

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

In [24]:
df.groupby("supervisor").agg({'units_produced':'sum',"defective_units":'sum'})

            units_produced  defective_units
supervisor
S1                    5231              209
S2                    6069              264
S3                    7418              273
S4                    5432              329

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

In [25]:
df.apply(lambda x: x['defective_units']/x['units_produced'],axis=1)

0     0.019139
1     0.053156
2     0.058559
3     0.046414
4     0.044118
5     0.045089
6     0.082621
7     0.013657
8     0.063796
9     0.043564
10    0.067729
11    0.050167
12    0.039683
13    0.008576
14    0.071111
15    0.019678
16    0.021739
17    0.078431
18    0.104956
19    0.025818
20    0.036090
21    0.021687
22    0.021583
23    0.095355
24    0.027708
25    0.090634
26    0.086253
27    0.057637
28    0.096346
29    0.044855
30    0.024316
31    0.026866
32    0.016207
33    0.049763
34    0.017799
35    0.033708
36    0.017214
37    0.052392
38    0.018692
39    0.086387
40    0.081800
41    0.017161
42    0.079487
43    0.034404
44    0.050104
45    0.020362
46    0.038217
47    0.052521
48    0.048338
49    0.065844
dtype: float64

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [26]:
df.groupby("factory")["profit"].apply(lambda x:x.max()-x.min())

factory
Plant_A    14199
Plant_B    14349
Plant_C    12745
Name: profit, dtype: int64

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [27]:
result=df.groupby('product_category',as_index=False).apply(lambda group: group[group['units_produced']==
                                                           group['units_produced'].max()]).reset_index()
result

,level_0,level_1,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,0,16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
1,1,2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
2,2,34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

In [31]:
df.apply(lambda x: x['units_produced']/x['production_time_hr'],axis=1)

0      95.288754
1      91.212121
2      85.824742
3      68.005739
4      53.363229
5      75.455650
6      47.885402
7      79.111645
8      87.569832
9      75.373134
10     72.438672
11     78.787879
12     42.567568
13     68.266979
14     64.562410
15     61.361142
16     84.975369
17     39.059081
18     38.324022
19     79.589041
20     86.363636
21     55.259654
22     45.227766
23     59.275362
24     58.468336
25     38.133641
26     52.624113
27     49.571429
28     41.232877
29     51.285521
30     39.878788
31     39.273154
32     79.510309
33     54.876463
34     91.964286
35     56.978233
36     68.562232
37     52.827918
38     63.126844
39     46.813725
40     70.461095
41     84.788360
42     59.360731
43     49.209932
44     53.459821
45     47.021277
46     34.392114
47     60.947503
48    101.689708
49     72.429210
dtype: float64

# Q14. Find how many times each product_category appears in the dataset.

In [32]:
df.product_category.value_counts()

Automotive     18
Electronics    16
Furniture      16
Name: product_category, dtype: int64

# Q15. Count the number of records for each shift.

In [33]:
df['shift'].value_counts()

Morning    22
Night      21
Evening     7
Name: shift, dtype: int64

# Q16. Find the most frequent supervisor using value_counts().

In [34]:
df.supervisor.value_counts().head(1)

S3    15
Name: supervisor, dtype: int64

# Q17. Sort the dataset by profit in descending order.

In [35]:
df.sort_values('profit',ascending=True)

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending

In [36]:
df.sort_values(['product_category','units_produced'],ascending=[True,False])

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673

In [37]:
df=pd.read_csv('IPL_Matches_2008_2022.csv')

In [53]:
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [47]:
# season wise most winning team with count

df.groupby("Season")['WinningTeam'].apply(lambda x:x.value_counts().head(1))

Season
2007/08  Rajasthan Royals         13
2009     Delhi Daredevils         10
2009/10  Mumbai Indians           11
2011     Chennai Super Kings      11
2012     Kolkata Knight Riders    12
2013     Mumbai Indians           13
2014     Kings XI Punjab          12
2015     Chennai Super Kings      10
2016     Sunrisers Hyderabad      11
2017     Mumbai Indians           12
2018     Chennai Super Kings      11
2019     Mumbai Indians           11
2020/21  Mumbai Indians           11
2021     Chennai Super Kings      11
2022     Gujarat Titans           12
Name: WinningTeam, dtype: int64

In [54]:
# teamwise man of the match-> no of player
df.groupby("WinningTeam")['Player_of_Match'].nunique()

WinningTeam
Chennai Super Kings            39
Deccan Chargers                19
Delhi Capitals                 16
Delhi Daredevils               39
Gujarat Lions                   7
Gujarat Titans                  9
Kings XI Punjab                42
Kochi Tuskers Kerala            4
Kolkata Knight Riders          44
Lucknow Super Giants            6
Mumbai Indians                 43
Pune Warriors                  11
Punjab Kings                   10
Rajasthan Royals               41
Rising Pune Supergiant          7
Rising Pune Supergiants         3
Royal Challengers Bangalore    36
Sunrisers Hyderabad            36
Name: Player_of_Match, dtype: int64

In [57]:
# 5 venue->where most m,atched being played
# team->which team dominate

new=pd.DataFrame()
new['count']=df.Venue.value_counts().head()

In [58]:
new=new.reset_index()
new

                                       index  count
0                               Eden Gardens     77
1                           Wankhede Stadium     73
2                      M Chinnaswamy Stadium     65
3                           Feroz Shah Kotla     60
4  Rajiv Gandhi International Stadium, Uppal     49

In [60]:
df1=new.merge(df,on="Venue",how="inner")

KeyError: 'Venue'

In [ ]:
df1.groupby("Venue")['WinningTeam'].apply(lambda x: x.value_counts().head(1))