In [1]:
import pandas as pd

import numpy as np

In [ ]:
quarter-1.csv

In [4]:
df1=pd.read_csv("quarter-1.csv")

In [5]:
df1

      order_id  quantity  item_id  choice_description_id item_price
0            1         1        1                      1     $3.39
1            1         1        2                      2     $3.39
2            2         2        4                      3    $16.98
3            4         1        7                      6     $9.25
4            6         1        9                      8     $8.75
...        ...       ...      ...                    ...        ...
2270      1831         1       16                      0     $1.50
2271      1833         1        6                    276    $11.75
2272      1833         1        6                    904    $11.75
2273      1834         1       20                    303     $8.75
2274      1834         1       20                     30     $8.75

[2275 rows x 5 columns]

In [7]:
df2=pd.read_csv("quarter-2.csv")

In [8]:
df3=pd.read_csv("quarter-3.csv")

In [12]:
d=pd.concat((df1,df2,df3),keys=["q1","q2","q3"])

In [21]:
d

        order_id quantity item_id choice_description_id item_price
q1 0           1        1       1                     1     $3.39
   1           1        1       2                     2     $3.39
   2           2        2       4                     3    $16.98
   3           4        1       7                     6     $9.25
   4           6        1       9                     8     $8.75
...          ...      ...     ...                   ...        ...
q2 2342     1829        1      23                    92    $11.25
   2343     1830        1      23                  1043    $11.25
   2344     1832        1      10                   116     $8.75
   2345     1832        1       8                     0     $4.45
   2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [14]:
d1=pd.read_csv("items.csv")

In [24]:
d1=d1.reset_index()

In [26]:
d1=d1.merge(d,on="item_id")

In [27]:
d1

,level_0,index,item_id,item_name,order_id,quantity,choice_description_id,item_price
0,0,0,0,Chips and Fresh Tomato Salsa,13,1,0,$2.39
1,0,0,0,Chips and Fresh Tomato Salsa,82,1,0,$2.95
2,0,0,0,Chips and Fresh Tomato Salsa,104,1,0,$2.95
3,0,0,0,Chips and Fresh Tomato Salsa,142,1,0,$2.39
4,0,0,0,Chips and Fresh Tomato Salsa,149,1,0,$2.95
...,...,...,...,...,...,...,...,...
4617,48,48,48,Veggie Salad,1094,1,755,$8.49
4618,48,48,48,Veggie Salad,1192,1,149,$8.49
4619,48,48,48,Veggie Salad,1263,1,306,$8.49
4620,48,48,48,Veggie Salad,1395,1,755,$8.49
4621,49,49,49,Carnitas Salad,1500,1,940,$8.99

In [32]:
d1

,level_0,index,item_id,item_name,order_id,quantity,choice_description_id,item_price
0,0,0,0,Chips and Fresh Tomato Salsa,13,1,0,$2.39
1,0,0,0,Chips and Fresh Tomato Salsa,82,1,0,$2.95
2,0,0,0,Chips and Fresh Tomato Salsa,104,1,0,$2.95
3,0,0,0,Chips and Fresh Tomato Salsa,142,1,0,$2.39
4,0,0,0,Chips and Fresh Tomato Salsa,149,1,0,$2.95
...,...,...,...,...,...,...,...,...
4617,48,48,48,Veggie Salad,1094,1,755,$8.49
4618,48,48,48,Veggie Salad,1192,1,149,$8.49
4619,48,48,48,Veggie Salad,1263,1,306,$8.49
4620,48,48,48,Veggie Salad,1395,1,755,$8.49
4621,49,49,49,Carnitas Salad,1500,1,940,$8.99

In [31]:
d1.groupby(["level_0","item_name"],as_index=False)["quantity"].sum().sort_values("quantity").max()

level_0                     49
item_name    Veggie Soft Tacos
quantity                   761
dtype: object

In [44]:
d1.groupby(["level_0","item_name"],as_index=False)["quantity"].sum().sort_values("quantity")

    level_0                              item_name  quantity
49       49                         Carnitas Salad         1
42       42      Chips and Mild Fresh Tomato Salsa         1
47       47                    Veggie Crispy Tacos         1
46       46                                  Salad         2
39       39                           Crispy Tacos         2
41       41                            Steak Salad         4
37       37                                   Bowl         4
38       38                                Burrito         6
44       44                    Carnitas Salad Bowl         6
48       48                           Veggie Salad         6
43       43                      Veggie Soft Tacos         8
40       40                  Carnitas Crispy Tacos         8
32       32                          Chicken Salad         9
45       45                    Barbacoa Salad Bowl        10
27       27                  Barbacoa Crispy Tacos        12
29       29     Chips and Roasted Chili-Corn Salsa        18
28       28                      Veggie Salad Bowl        18
1         1                                   Izze        20
30       30     Chips and Roasted Chili Corn Salsa        23
22       22                    Barbacoa Soft Tacos        25
36       36    Chips and Tomatillo-Red Chili Salsa        25
2         2                       Nantucket Nectar        29
34       34                       Steak Salad Bowl        31
3         3  Chips and Tomatillo-Green Chili Salsa        33
25       25                     Steak Crispy Tacos        36
31       31                    Carnitas Soft Tacos        40
17       17  Chips and Tomatillo Green Chili Salsa        45
26       26    Chips and Tomatillo Red Chili Salsa        50
9         9                   Chicken Crispy Tacos        50
35       35                      6 Pack Soft Drink        55
7         7                       Steak Soft Tacos        56
14       14                       Carnitas Burrito        60
18       18                          Barbacoa Bowl        66
15       15                          Carnitas Bowl        71
24       24                            Veggie Bowl        87
13       13                       Barbacoa Burrito        91
23       23                         Veggie Burrito        97
5         5                          Side of Chips       110
10       10                     Chicken Soft Tacos       120
20       20                     Chicken Salad Bowl       123
12       12                            Canned Soda       126
0         0           Chips and Fresh Tomato Salsa       130
16       16                          Bottled Water       211
21       21                             Steak Bowl       221
19       19                                  Chips       230
33       33                      Canned Soft Drink       351
6         6                          Steak Burrito       386
8         8                    Chips and Guacamole       506
11       11                        Chicken Burrito       591
4         4                           Chicken Bowl       761

In [33]:
d1.groupby(["level_0","item_name"],as_index=False)["quantity"].sum().sort_values("quantity",ascending=False).drop_duplicates(subset=["level_0"])

    level_0                              item_name  quantity
4         4                           Chicken Bowl       761
11       11                        Chicken Burrito       591
8         8                    Chips and Guacamole       506
6         6                          Steak Burrito       386
33       33                      Canned Soft Drink       351
19       19                                  Chips       230
21       21                             Steak Bowl       221
16       16                          Bottled Water       211
0         0           Chips and Fresh Tomato Salsa       130
12       12                            Canned Soda       126
20       20                     Chicken Salad Bowl       123
10       10                     Chicken Soft Tacos       120
5         5                          Side of Chips       110
23       23                         Veggie Burrito        97
13       13                       Barbacoa Burrito        91
24       24                            Veggie Bowl        87
15       15                          Carnitas Bowl        71
18       18                          Barbacoa Bowl        66
14       14                       Carnitas Burrito        60
7         7                       Steak Soft Tacos        56
35       35                      6 Pack Soft Drink        55
9         9                   Chicken Crispy Tacos        50
26       26    Chips and Tomatillo Red Chili Salsa        50
17       17  Chips and Tomatillo Green Chili Salsa        45
31       31                    Carnitas Soft Tacos        40
25       25                     Steak Crispy Tacos        36
3         3  Chips and Tomatillo-Green Chili Salsa        33
34       34                       Steak Salad Bowl        31
2         2                       Nantucket Nectar        29
22       22                    Barbacoa Soft Tacos        25
36       36    Chips and Tomatillo-Red Chili Salsa        25
30       30     Chips and Roasted Chili Corn Salsa        23
1         1                                   Izze        20
28       28                      Veggie Salad Bowl        18
29       29     Chips and Roasted Chili-Corn Salsa        18
27       27                  Barbacoa Crispy Tacos        12
45       45                    Barbacoa Salad Bowl        10
32       32                          Chicken Salad         9
43       43                      Veggie Soft Tacos         8
40       40                  Carnitas Crispy Tacos         8
48       48                           Veggie Salad         6
44       44                    Carnitas Salad Bowl         6
38       38                                Burrito         6
41       41                            Steak Salad         4
37       37                                   Bowl         4
39       39                           Crispy Tacos         2
46       46                                  Salad         2
42       42      Chips and Mild Fresh Tomato Salsa         1
47       47                    Veggie Crispy Tacos         1
49       49                         Carnitas Salad         1

In [39]:
d1["item_price"].apply(lambda x: float(x[1:]))

0       2.39
1       2.95
2       2.95
3       2.39
4       2.95
        ...
4617    8.49
4618    8.49
4619    8.49
4620    8.49
4621    8.99
Name: item_price, Length: 4622, dtype: float64

In [40]:
d1.dtypes

level_0                   int64
index                     int64
item_id                  object
item_name                object
order_id                 object
quantity                 object
choice_description_id    object
item_price               object
dtype: object

In [41]:
d1["total"]=d1["item_price"]*d1["quantity"]

In [42]:
d1

,level_0,index,item_id,item_name,order_id,quantity,choice_description_id,item_price,total
0,0,0,0,Chips and Fresh Tomato Salsa,13,1,0,$2.39,$2.39
1,0,0,0,Chips and Fresh Tomato Salsa,82,1,0,$2.95,$2.95
2,0,0,0,Chips and Fresh Tomato Salsa,104,1,0,$2.95,$2.95
3,0,0,0,Chips and Fresh Tomato Salsa,142,1,0,$2.39,$2.39
4,0,0,0,Chips and Fresh Tomato Salsa,149,1,0,$2.95,$2.95
...,...,...,...,...,...,...,...,...,...
4617,48,48,48,Veggie Salad,1094,1,755,$8.49,$8.49
4618,48,48,48,Veggie Salad,1192,1,149,$8.49,$8.49
4619,48,48,48,Veggie Salad,1263,1,306,$8.49,$8.49
4620,48,48,48,Veggie Salad,1395,1,755,$8.49,$8.49
4621,49,49,49,Carnitas Salad,1500,1,940,$8.99,$8.99

In [43]:
d1.total

0       $2.39
1       $2.95
2       $2.95
3       $2.39
4       $2.95
         ...
4617    $8.49
4618    $8.49
4619    $8.49
4620    $8.49
4621    $8.99
Name: total, Length: 4622, dtype: object

In [52]:
d1.groupby(["level_0","item_name"],as_index=False)["total"].sum().sort_values("total",ascending=False).drop_duplicates(subset=["level_0"])

,level_0,item_name,total
31,31,Carnitas Soft Tacos,$9.25 $9.25 $9.25 $8.99 $8.99 $9.25 $9.25 $9.2...
22,22,Barbacoa Soft Tacos,$9.25 $9.25 $9.25 $11.75 $11.75 $9.25 $11.75 $...
7,7,Steak Soft Tacos,$9.25 $8.99 $9.25 $9.25 $8.99 $9.25 $9.25 $8.9...
13,13,Barbacoa Burrito,$9.25 $11.75 $11.75 $8.99 $8.99 $9.25 $9.25 $9...
41,41,Steak Salad,$8.99 $8.99 $8.99 $8.69
25,25,Steak Crispy Tacos,$8.99 $8.69 $9.25 $9.25 $9.25 $9.25 $11.75 $8....
15,15,Carnitas Bowl,$8.99 $11.75 $11.48 $8.99 $8.99 $23.50 $23.50 ...
49,49,Carnitas Salad,$8.99
10,10,Chicken Soft Tacos,$8.75 $8.75 $8.49 $8.49 $17.50 $17.50 $8.75 $1...
43,43,Veggie Soft Tacos,$8.75 $8.75 $11.25 $8.49 $11.25 $8.49 $16.98 $...
20,20,Chicken Salad Bowl,$8.75 $22.50 $22.50 $22.50 $22.50 $8.75 $17.50...
9,9,Chicken Crispy Tacos,$8.75 $17.50 $17.50 $11.25 $8.75 $11.25 $8.75 ...
48,48,Veggie Salad,$8.49 $8.49 $8.49 $8.49 $8.49 $8.49
11,11,Chicken Burrito,$8.49 $8.49 $10.98 $10.98 $8.49 $10.98 $11.25 ...
23,23,Veggie Burrito,$8.49 $11.25 $11.25 $11.25 $8.49 $8.49 $8.49 $...
47,47,Veggie Crispy Tacos,$8.49
38,38,Burrito,$7.40 $7.40 $7.40 $7.40 $7.40 $7.40
46,46,Salad,$7.40 $7.40
39,39,Crispy Tacos,$7.40 $7.40
35,35,6 Pack Soft Drink,$6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.4...
8,8,Chips and Guacamole,$4.45 $4.45 $4.45 $4.45 $4.45 $4.45 $4.45 $4.4...
2,2,Nantucket Nectar,$3.39 $3.39 $3.39 $3.39 $6.78 $6.78 $3.39 $3.3...
1,1,Izze,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.3...
42,42,Chips and Mild Fresh Tomato Salsa,$3.00
34,34,Steak Salad Bowl,$23.78 $23.78 $11.89 $23.78 $23.78 $11.89 $11....
37,37,Bowl,$22.20 $22.20 $22.20 $7.40
17,17,Chips and Tomatillo Green Chili Salsa,$2.95 $2.95 $5.90 $5.90 $2.95 $5.90 $5.90 $2.9...
26,26,Chips and Tomatillo Red Chili Salsa,$2.95 $2.95 $2.95 $2.95 $5.90 $5.90 $2.95 $2.9...
30,30,Chips and Roasted Chili Corn Salsa,$2.95 $2.95 $2.95 $2.95 $2.95 $5.90 $5.90 $2.9...
0,0,Chips and Fresh Tomato Salsa,$2.39 $2.95 $2.95 $2.39 $2.95 $2.95 $2.95 $2.2...
36,36,Chips and Tomatillo-Red Chili Salsa,$2.39 $2.39 $2.39 $7.17 $7.17 $7.17 $2.39 $2.3...
3,3,Chips and Tomatillo-Green Chili Salsa,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
29,29,Chips and Roasted Chili-Corn Salsa,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
12,12,Canned Soda,$2.18 $2.18 $1.09 $1.09 $1.09 $2.18 $2.18 $1.0...
19,19,Chips,$2.15 $2.15 $4.30 $4.30 $2.15 $2.15 $2.15 $2.1...
4,4,Chicken Bowl,$16.98 $16.98 $11.25 $8.49 $11.25 $8.75 $8.75 ...
45,45,Barbacoa Salad Bowl,$11.89 $11.89 $11.89 $9.39 $9.39 $11.89 $9.39 ...
44,44,Carnitas Salad Bowl,$11.89 $11.89 $11.89 $9.39 $11.89 $9.39
14,14,Carnitas Burrito,$11.75 $9.25 $9.25 $9.25 $11.75 $8.99 $9.25 $9...
6,6,Steak Burrito,$11.75 $8.99 $8.99 $8.99 $8.99 $8.99 $8.99 $8....
40,40,Carnitas Crispy Tacos,$11.75 $17.98 $17.98 $9.25 $9.25 $11.75 $8.99 ...
18,18,Barbacoa Bowl,$11.75 $11.75 $9.25 $11.48 $9.25 $9.25 $9.25 $...
21,21,Steak Bowl,$11.75 $11.75 $11.48 $9.25 $11.75 $11.75 $9.25...
27,27,Barbacoa Crispy Tacos,$11.48 $9.25 $8.99 $18.50 $18.50 $8.99 $11.75 ...
28,28,Veggie Salad Bowl,$11.25 $8.75 $11.25 $8.75 $8.75 $11.25 $11.25 ...
24,24,Veggie Bowl,$11.25 $8.49 $11.25 $8.75 $8.75 $11.25 $8.49 $...
32,32,Chicken Salad,$10.98 $8.49 $8.49 $8.19 $10.98 $8.49 $8.49 $8...
5,5,Side of Chips,$1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.6...
33,33,Canned Soft Drink,$1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.2...
16,16,Bottled Water,$1.09 $1.09 $1.50 $1.50 $1.50 $3.00 $3.00 $1.5...

In [48]:
d1

,level_0,index,item_id,item_name,order_id,quantity,choice_description_id,item_price,total
0,0,0,0,Chips and Fresh Tomato Salsa,13,1,0,$2.39,$2.39
1,0,0,0,Chips and Fresh Tomato Salsa,82,1,0,$2.95,$2.95
2,0,0,0,Chips and Fresh Tomato Salsa,104,1,0,$2.95,$2.95
3,0,0,0,Chips and Fresh Tomato Salsa,142,1,0,$2.39,$2.39
4,0,0,0,Chips and Fresh Tomato Salsa,149,1,0,$2.95,$2.95
...,...,...,...,...,...,...,...,...,...
4617,48,48,48,Veggie Salad,1094,1,755,$8.49,$8.49
4618,48,48,48,Veggie Salad,1192,1,149,$8.49,$8.49
4619,48,48,48,Veggie Salad,1263,1,306,$8.49,$8.49
4620,48,48,48,Veggie Salad,1395,1,755,$8.49,$8.49
4621,49,49,49,Carnitas Salad,1500,1,940,$8.99,$8.99

In [50]:
d

        order_id quantity item_id choice_description_id item_price
q1 0           1        1       1                     1     $3.39
   1           1        1       2                     2     $3.39
   2           2        2       4                     3    $16.98
   3           4        1       7                     6     $9.25
   4           6        1       9                     8     $8.75
...          ...      ...     ...                   ...        ...
q2 2342     1829        1      23                    92    $11.25
   2343     1830        1      23                  1043    $11.25
   2344     1832        1      10                   116     $8.75
   2345     1832        1       8                     0     $4.45
   2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [54]:
d1.groupby(["level_0",'order_id'],as_index=False)["total"].sum()

      level_0  order_id   total
0           0         1  $2.39
1           0        13  $2.39
2           0        25  $2.39
3           0        39  $2.95
4           0        82  $2.95
...       ...       ...     ...
4287       48      1192  $8.49
4288       48      1263  $8.49
4289       48      1395  $8.49
4290       48      1635  $8.49
4291       49      1500  $8.99

[4292 rows x 3 columns]